### ISSUE TITLE
FastStructure example

### ISSUE THREAD

**Issue by quicktrick** [spazzarama/SharedMemory#22]
Hi Justin,

Could you please give an example of how to use `FastStructure` in client/server applications?  The examples on [your site](http://spazzarama.com/2015/12/31/fast-shared-array-buffer-and-circular-buffer-ring-buffer-for-dotnet-ipc-with-memory-mapped-files/) and in the `FastStructureTests.cs` aren't clear about that (besides, this is a new subject for me). In fact, I don't get how to pass `IntPtr` between the applications.

And some more questions if you don't mind.

1. Why do you use `unsafe` keyword in the test method `FastStructure_AllocHGlobalReadWrite()`?

            unsafe
            {
                n.Compatible.Contents[0] = 4;
                n.Compatible.Contents[7] = 5;
            }

2. Don't you need to set `StructLayoutAttribute.Pack` field when instantiating `StructLayoutAttribute`, as shown [here](https://msdn.microsoft.com/en-us/library/system.runtime.interopservices.structlayoutattribute.pack(v=vs.110).aspx)? Or the default value `Pack=0` is ok in this case?

3. Is it possible to use `DateTime`/`TimeSpan` structures (and nested structures) in the non-generic version of `FastStructure`, or I need to convert them to `long`s?

Thank you in advance!

Alex

**Comment by quicktrick** [comment]
I've managed to pass `IntPtr` to another application using SharedBuffer. Everything is working, but there are some nuances I have to cope with to make it work in real applications.

**Comment by quicktrick** [comment]
Many many thanks for your library, Justin!  It works like a charm!  My server (consumer) gets data faster than the client (provider) makes some primitive manipulations with them after sending them to server! :) 👍

**Comment by spazzarama** [comment]
@quicktrick I'm glad you found it useful. Sorry for not getting to this sooner but looks like you have it all sorted. Enjoy!

**Comment by spazzarama** [comment]
For others that come here looking for further examples (including nested structure support). Take a look at the FastStructure unit tests:

https://github.com/spazzarama/SharedMemory/blob/master/SharedMemoryTests/FastStructureTests.cs
