### ISSUE TITLE
SharedArray - Windows Service

### ISSUE THREAD

**Issue by pavelsommer** [spazzarama/SharedMemory#28]
Hi, I'm trying create SharedArray<T> inside Windows Service and open it in desktop app and I am getting the Unable to find the specified file exception. It is somehow possible to resolve this task and share data between Windows Service and desktop app?

**Comment by spazzarama** [comment]
@pavelsommer try the following: https://stackoverflow.com/a/43802332/323899

From what it says, you can prefix the name of the mapped memory with Global/ and it will be available across sessions.
