### ISSUE TITLE
Need a Circuler Buffer Example.

### ISSUE THREAD

**Issue by imkaka** [spazzarama/SharedMemory#32]
> I want to implement a Shared Memory Server which can always wait to new stuff to be written and print that, (To hold the server always Open and Write Whenever there is new Write in Mem)
> and a client process which will open write and close.(It is basic).

> I come to know that this Library has implemented it via CodeProject But I don't know how can i use it as there are no such examples.

**Comment by spazzarama** [comment]
@imkaka there is an example of how to open/create the server (producer) and open the client (consumer) in the readme, and in the example projects.

In the server:
```
using (var producer = new SharedMemory.CircularBuffer(name: "MySharedMemory", nodeCount: 3, nodeBufferSize: 4))
{
    // TODO: your server write loop
    // Example:
    for (var i = 0; i < 50; i++)
    {
        // nodeCount must be one larger than the number
        // of writes that must fit in the buffer at any one time
        producer.Write<int>(new int[] { i });
    }
}
```

In the client:
```
using (var consumer = new SharedMemory.CircularBuffer(name: "MySharedMemory"))
{
    // TODO: your client read loop/read trigger
    // Example:
    int[] data = new int[1];
    int i = 0;
    while (i < 49)
    {
        consumer.Read<int>(data);
        i = data[0];
        Console.WriteLine(i);
    }
}
```
