### ISSUE TITLE
Not fully compatible with netstandard20

### ISSUE THREAD

**Issue by ugumba** [spazzarama/SharedMemory#33]
Hi,
I'm referencing the package from a netstandard2.0 project, and VS displays this warning:

> warning NU1701: Package 'SharedMemory 2.1.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.

Is this expected?  Are there any risks in ignoring this warning?

Edit: I guess the library projects should target netstandard2.0 instead of netcoreapp2.0.

Brgds,
Robert

**Comment by spazzarama** [comment]
The reason it originally targeted netcoreapp2.0 was because it uses DynamicMethod from System.Reflection.Emit which was not available.

Will send new PR that includes the new dependency in NuGet also.

**Comment by ugumba** [comment]
Ah, makes sense. Thanks!
