### ISSUE TITLE
Where to call AcquireWriteLock/AcquireReadLock

### ISSUE THREAD

**Issue by wenris** [spazzarama/SharedMemory#41]
In BufferWithLocks, any Write/Read memthod just call WriteWait/ReadWait to check that WriteWaitEvent/ReadWaitEvent is set, but not acqire locks, why?

Should I call AcquireWriteLock/AcquireReadLock in my userland code?

**Comment by wenris** [comment]
```
private void WriteWait()
        {
            if (!WriteWaitEvent.WaitOne(ReadWriteTimeout))
                throw new TimeoutException("The write operation timed out waiting for the write lock WaitEvent. Check your usage of AcquireWriteLock/ReleaseWriteLock and AcquireReadLock/ReleaseReadLock.");
        }
```

**Comment by spazzarama** [comment]
@wenris depends on your code, if you need to asynchronously support read/write and want to ensure that the read waits for the write, then yes, manually call AcquireRead/WriteLocks at the appropriate times based on your logic (remember to release them also).

If you AcquireReadLock, then writing is blocked until your read lock is released. If AcquireWriteLock then reading is blocked until you release it.

**Comment by wenris** [comment]
Is SharedArray/CircularArray thread-safe?

**Comment by spazzarama** [comment]
CircularBuffer is thread-safe, no locks required - it internally manages the circular buffer in such a way it is impossible to write over a node while reading.

SharedArray is thread-safe if you use the AcquireRead/WriteLocks and ReleaseRead/WriteLocks around the read/writes. You can read and write to different indexes without locks if that suits the implementation. If you want an implementation that automatically acquires and releases locks upon read/write (and you only need a single read/write at a time), then simply create a class inheriting from SharedArray and override the Read/Write to acquire and release the appropriate locks around a call to the original Read/Write methods.
